<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit5ab7e8ef5d2cf8fdf8f84e7283728f8b
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('ComposerAutoloaderInit5ab7e8ef5d2cf8fdf8f84e7283728f8b', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit5ab7e8ef5d2cf8fdf8f84e7283728f8b', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Composer\Autoload\ComposerStaticInit5ab7e8ef5d2cf8fdf8f84e7283728f8b::getInitializer($loader));

        $loader->register(true);

        return $loader;
    }
}
